# Generated by Django 5.1.1 on 2024-09-05 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_event_participants_eventtoparticipant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                through="events.EventToParticipant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
